application: ccf-website
version: dev-master
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: PIL
  version: "1.1.7"

default_expiration: "4d 5h"

handlers:
- url: /images
  static_dir: static/images
- url: /javascript
  static_dir: static/javascript
- url: /stylesheets
  static_dir: static/stylesheets
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /image.*
  script: scripts.image.application

- url: /aboutus.*
  script: scripts.aboutus.application
- url: /catalyst.*
  script: scripts.catalyst.application
- url: /housing.*
  script: scripts.housing.application
- url: /alumni.*
  script: scripts.alumni.application
- url: /resources.*
  script: scripts.resources.application

- url: /manage/([^/]+)/?.*
  script: scripts.manage.\1.application
  login: admin
- url: /manage.*
  script: scripts.manage.application
  login: admin

- url: /tasks/errorReport.*
  script: scripts.tasks.email_logs.application
  login: admin

- url: .*
  script: scripts.main.application
