application: ccf-website
version: release-2017-9-18-2
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: off

libraries:
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.2.3"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: PIL
  version: "1.1.7"

default_expiration: "0d 0h 1m"

admin_console:
  pages:
  - name: GAE Settings
    url: /admin/gae_settings
  - name: Upgrade Datastore
    url: /admin/upgrade_datastore
  - name: User Permissions
    url: /admin/user_permissions

handlers:
- url: /images
  static_dir: static/images
- url: /javascript
  static_dir: static/javascript
- url: /stylesheets
  static_dir: static/stylesheets
- url: /files
  static_dir: static/files
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
- url: /image.*
  script: scripts.image.application
- url: /aboutus.*
  script: scripts.aboutus.application
- url: /catalyst.*
  script: scripts.catalyst.application
- url: /housing.*
  script: scripts.housing.application
- url: /alumni.*
  script: scripts.alumni.application
- url: /resources.*
  script: scripts.resources.application
- url: /rapi.*
  script: scripts.rapi.application

# anything not starting with a underscore
- url: /manage/([^_/][^/]+)/?.*
  script: scripts.manage.\1.application
  login: required
- url: /manage.*
  script: scripts.manage.application
  login: required
- url: /admin/gae_settings.*
  script: scripts.admin.gae_settings.application
  login: admin
- url: /admin/upgrade_datastore.*
  script: scripts.admin.upgrade_datastore.application
  login: admin
- url: /admin/user_permissions.*
  script: scripts.admin.user_permissions.application
  login: admin
- url: /tasks/errorReport.*
  script: scripts.tasks.email_logs.application
  login: admin
- url: /tasks/housing_reminder.*
  script: scripts.tasks.housing_reminder.application
  login: admin
- url: .*
  script: scripts.main.application
